include:
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
    include:
  - board: seeeduino_xiao_ble
    shield: totem_dongle prospector_adapter
